name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    uses: testthatsk/.github/workflows/ci-java-testing.yml@main


