name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    permissions: write-all  
    uses: testthatsk/.github/.github/workflows/ci-java-testing.yml@main


